### PR TITLE
Porchctl repo command fixes

### PR DESCRIPTION
**Pull request by dgeorgievski**
Fixes for `porchctl repo` command described in https://github.com/nephio-project/nephio/issues/755 issue.

I wasn't sure what approach to take for testing the repo commands. I see that `repo reg` command is using fake porch server. Should I follow suit for `repo reg` command?

### CODE REVIEW

**Comment by dgeorgievski** [comment]
Question about the CLA agreement. Axyom.core , my employer, is interested to sign the corporate CLA. I have a question for the email and GitHub account used in this PR. 

So far, I've been working with my personal GitHub account and email address. Would I need to re-submit the PR with the corproate email and GitHub account linked to it?

**Comment by dgeorgievski** [comment]
I am closing this PR and will open a new one with Axyom.Core credentials to be able to submit Corporate CLA request.

**Comment by dgeorgievski** [comment]
Easy CLA signed

**Comment by liamfallon** [comment]
> Easy CLA signed

It seems there is still some problem with the CLA, the check is not passing.Maybe submit a support request on the link above.

**Comment by dgeorgievski** [comment]
> > > Easy CLA signed
> > 
> > 
> > It seems there is still some problem with the CLA, the check is not passing.Maybe submit a support request on the link above.
> 
> I have received a copy of the signed agreement, so I am not sure why the check is failing. I will contact support.

EasyCLA fixed. Proceeding with the next steps. Again, thank you for patience.

**Review by liamfallon — COMMENTED** [review]
@dgeorgievski thanks for the contribution!

/approve
/lgtm

**Pull request merged**
