### PR TITLE
Fix generate

### PR DESCRIPTION
**Pull request by johnbelamaric**
This is a WIP that shows some of the changes needed to fix the `make generate` target. We may be better off reworking some of the code gen, I am not sure. I couldn't get some of it to work without spending more time digging into the tools.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Basically, someone just has to go through file by file and try out the various `go:generate` directives and get them to work...

```console
[hi on] jbelamaric@jbelamaric:~/proj/gh/johnbelamaric/porch$ grep -r go:generate .
./api/porchconfig/v1alpha1/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../scripts/boilerplate.go.txt" crd:crdVersions=v1 output:crd:artifacts:config=. paths=./...
./api/porch/doc.go://go:generate go run k8s.io/code-generator/cmd/deepcopy-gen --input-dirs ../porch,v1alpha1 -O zz_generated.deepcopy --go-header-file ../../scripts/boilerplate.go.txt
./api/porch/doc.go://go:generate go run k8s.io/code-generator/cmd/openapi-gen --input-dirs github.com/nephio-project/porch/api/porch/v1alpha1 --input-dirs k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/version -p ../generated/openapi -O zz_generated.openapi --go-header-file ../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/deepcopy-gen@v0.25.3 --input-dirs ../v1alpha1 -O zz_generated.deepcopy --go-header-file ../../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/defaulter-gen --input-dirs ../v1alpha1 -O zz_generated.defaults --go-header-file ../../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/client-gen --clientset-name versioned --input-base "" --input porch/v1alpha1 -p ../../generated/clientset --plural-exceptions PackageRevisionResources:PackageRevisionResources --go-header-file ../../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/lister-gen --input-dirs github.com/nephio-project/porch/api/porch/v1alpha1 -p ../../generated/listers --go-header-file ../../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/informer-gen --input-dirs github.com/nephio-project/porch/api/porch/v1alpha1 --versioned-clientset-package github.com/nephio-project/porch/api/generated/clientset/versioned --listers-package github.com/nephio-project/porch/api/generated/listers --internal-clientset-package github.com/nephio-project/porch/api/generated/informers/internalversion -p github.com/nephio-project/porch/api/generated/informers --plural-exceptions PackageRevisionResources:PackageRevisionResources --go-header-file ../../../scripts/boilerplate.go.txt
./api/porch/v1alpha1/doc.go://go:generate go run k8s.io/code-generator/cmd/conversion-gen --input-dirs ../../porch,../v1alpha1 -O zz_generated.conversion --go-header-file ../../../scripts/boilerplate.go.txt
./internal/api/porchinternal/v1alpha1/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../scripts/boilerplate.go.txt" crd:crdVersions=v1 output:crd:artifacts:config=. paths=./...
./pkg/kpt/api/kptfile/v1/types.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../porch/scripts/boilerplate.go.txt"
./pkg/git/git.go://go:generate go run golang.org/x/tools/cmd/stringer -type=MainBranchStrategy -linecomment
./controllers/packagevariants/api/v1alpha1/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../scripts/boilerplate.go.txt" paths="./..."
./controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 rbac:roleName=porch-controllers-packagevariants webhook paths="." output:rbac:artifacts:config=../../../config/rbac
./controllers/fleetsyncs/api/v1alpha1/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../scripts/boilerplate.go.txt" paths="./..."
./controllers/fleetsyncs/pkg/controllers/fleetsync/controller.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 rbac:roleName=porch-controllers-fleetsyncs webhook paths="." output:rbac:artifacts:config=../../../config/rbac
./controllers/packagevariantsets/api/v1alpha2/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../scripts/boilerplate.go.txt" paths="./..."
./controllers/packagevariantsets/api/v1alpha1/groupversion_info.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 object:headerFile="../../../../scripts/boilerplate.go.txt" paths="./..."
./controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 rbac:roleName=porch-controllers-packagevariantsets webhook paths="." output:rbac:artifacts:config=../../../config/rbac
./controllers/main.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 rbac:roleName=porch-controllers webhook paths="."
./controllers/main.go://go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0 crd paths="./..." output:crd:artifacts:config=config/crd/bases
```

**Comment by liamfallon** [comment]
@johnbelamaric I guess we can close this one now that https://github.com/nephio-project/porch/pull/35 is merged?

**Comment by johnbelamaric** [comment]
/close

Thanks for the great work :)

**Pull request closed without merging**
